#version: "3.9"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.7
    ports:
      - "8123:8123"
    volumes:
      - ch_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: meta
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2024-09-22T00-33-43Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  api:
    build:
      context: ../..
      dockerfile: infra/docker/api.Dockerfile
    environment:
      TP_ENV: DEV
    depends_on:
      - clickhouse
      - postgres
      - minio
    ports:
      - "8000:8000"
    volumes:
      - ../../:/app
    command: uvicorn apps.api.main:app --host 0.0.0.0 --port 8000 --reload  # ✅ hot loading

  scheduler:
    build:
      context: ../..
      dockerfile: infra/docker/scheduler.Dockerfile
    environment:
      TP_ENV: DEV
      S3_ENDPOINT_URL: http://minio:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      S3_BUCKET_RAW: raw
      S3_BUCKET_CLEAN: clean
    depends_on:
      - clickhouse
      - postgres
      - minio

  worker:
    build:
      context: ../..
      dockerfile: infra/docker/worker.Dockerfile
    environment:
      TP_ENV: DEV
      S3_ENDPOINT_URL: http://minio:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      S3_BUCKET_RAW: raw
      S3_BUCKET_CLEAN: clean
    depends_on:
      - clickhouse
      - postgres
      - minio

volumes:
  ch_data: {}
  pg_data: {}
  minio_data: {}
