ENV: PROD
LOG_LEVEL: INFO
CLICKHOUSE:
HOST: ${CLICKHOUSE_HOST}
PORT: 8123
USER: ${CLICKHOUSE_USER}
PASSWORD: ${CLICKHOUSE_PASSWORD}
DATABASE: market
S3:
ENDPOINT_URL: ${S3_ENDPOINT}
ACCESS_KEY: ${S3_ACCESS_KEY}
SECRET_KEY: ${S3_SECRET_KEY}
BUCKET_RAW: raw
BUCKET_CLEAN: clean
POSTGRES:
HOST: ${PG_HOST}
PORT: 5432
USER: ${PG_USER}
PASSWORD: ${PG_PASSWORD}
DATABASE: meta
API:
HOST: 0.0.0.0
PORT: 8000
PREFECT:
ENABLED: true
QUEUE: default